### ISSUE TITLE
Put constants into json mapping

### ISSUE THREAD

**Issue by ketchupok** [cosmoproject/cosmo-dsp#8]
through the automatic add of 'gk' to variables, its no longer possible to put simple values

**Comment by berntisak** [comment]
I already fixed this

**Comment by ketchupok** [comment]
still not working.. see Reverb line...
		aL, aR Hack aL, aR, gkCC23_CH1, gkCC21_CH1
		aL, aR AnalogDelay aL, aR, gkCC21_CH1, gkCC22_CH1, gkCC23_CH1
		aL, aR Reverse aL, aR, 0.5, gkCC22_CH1
		aL, aR Reverb aL, aR, gk0.9, 0.5, 0.5

**Comment by berntisak** [comment]
My bad - worked first, but then a change broke it. Checking to see if it's a floating point number instead now and making gk variables of everything that's not.
